Add check for Debian system - workaround for Debian patch
Seems that Debian patched pip and this causes the following error:
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base

See here for some previous discussion:
https://github.com/pypa/pip/issues/3826

I added the --system and it seems to have resolved this for me, I'm no export though so would be good to get it tested with more Debian users (I'm using Ubuntu on Windows 10/WSL - because Windows 10 doesn't like long paths)

There is very probably a much better way of doing this so feel free to ignore this change request 😄